# Generated by Django 5.1.7 on 2025-06-02 08:45

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_rename_name_digitalclinic_clinic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalclinicmedicalrecords',
            old_name='digital_clinic_name',
            new_name='digital_clinic_id',
        ),
        migrations.RenameField(
            model_name='digitalclinicpaymentinformation',
            old_name='digital_clinic_name',
            new_name='digital_clinic_id',
        ),
        migrations.AddField(
            model_name='digitalclinic',
            name='owner_name',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
